app/Http/routes.php
<?php

/*
 * Include our API routes file
 */
include_once('api_routes.php');

/*
 * -------------------------
 * Installer
 * -------------------------
 */
Route::get('install', [
    'as'   => 'showInstaller',
    'uses' => 'InstallerController@showInstaller',
]);
Route::post('install', [
    'as'   => 'postInstaller',
    'uses' => 'InstallerController@postInstaller',
]);

/*
 * Stripe connect return
 */
Route::any('payment/return/stripe', [
    'as'   => 'showStripeReturn',
    'uses' => 'ManageAccountController@showStripeReturn',
]);

/*
 * Logout
 */
Route::any('/logout', [
    'uses' => 'UserLogoutController@doLogout',
    'as'   => 'logout',
]);

Route::group(['middleware' => ['installed']], function () {

    /*
     * Login
     */
    Route::get('/login', [
        'as'   => 'login',
        'uses' => 'UserLoginController@showLogin',
    ]);
    Route::post('/login', 'UserLoginController@postLogin');

    /*
     * Forgot password
     */
    Route::get('login/forgot-password', [
        'as'   => 'forgotPassword',
        'uses' => 'RemindersController@getRemind',
    ]);

    Route::post('login/forgot-password', [
        'as'   => 'postForgotPassword',
        'uses' => 'RemindersController@postRemind',
    ]);

    /*
     * Reset Password
     */
    Route::get('login/reset-password/{token}', [
        'as'   => 'showResetPassword',
        'uses' => 'RemindersController@getReset',
    ]);

    Route::post('login/reset-password', [
        'as'   => 'postResetPassword',
        'uses' => 'RemindersController@postReset',
    ]);

    /*
     * Registration / Account creation
     */
    Route::get('/signup', [
        'uses' => 'UserSignupController@showSignup',
        'as'   => 'showSignup',
    ]);
    Route::post('/signup', 'UserSignupController@postSignup');

    /*
     * Confirm Email
     */
    Route::get('signup/confirm_email/{confirmation_code}', [
        'as'   => 'confirmEmail',
        'uses' => 'UserSignupController@confirmEmail',
    ]);
});

/*
 * Public organiser page routes
 */
Route::group(['prefix' => 'o'], function () {

    Route::get('/{organiser_id}/{organier_slug?}', [
        'as'   => 'showOrganiserHome',
        'uses' => 'OrganiserViewController@showOrganiserHome',
    ]);

});

/*
 * Public event page routes
 */
Route::group(['prefix' => 'e'], function () {

    /*
     * Embedded events
     */
    Route::get('/{event_id}/embed', [
        'as'   => 'showEmbeddedEventPage',
        'uses' => 'EventViewEmbeddedController@showEmbeddedEvent',
    ]);

    Route::get('/{event_id}/{event_slug?}', [
        'as'   => 'showEventPage',
        'uses' => 'EventViewController@showEventHome',
    ]);

    Route::post('/{event_id}/contact_organiser', [
       'as'    => 'postContactOrganiser',
        'uses' => 'EventViewController@postContactOrganiser',
    ]);

    /*
     * Used for previewing designs in the backend. Doesn't log page views etc.
     */
    Route::get('/{event_id}/preview', [
        'as'   => 'showEventPagePreview',
        'uses' => 'EventViewController@showEventHomePreview',
    ]);

    Route::post('{event_id}/checkout/', [
        'as'   => 'postValidateTickets',
        'uses' => 'EventCheckoutController@postValidateTickets',
    ]);

    Route::get('{event_id}/checkout/create', [
        'as'   => 'showEventCheckout',
        'uses' => 'EventCheckoutController@showEventCheckout',
    ]);

    Route::get('{event_id}/checkout/success', [
        'as'   => 'showEventCheckoutPaymentReturn',
        'uses' => 'EventCheckoutController@showEventCheckoutPaymentReturn',
    ]);



    Route::post('{event_id}/checkout/create', [
        'as'   => 'postCreateOrder',
        'uses' => 'EventCheckoutController@postCreateOrder',
    ]);
});

/*
 * Public view order routes
 */
Route::get('order/{order_reference}', [
    'as'   => 'showOrderDetails',
    'uses' => 'EventCheckoutController@showOrderDetails',
]);

Route::get('order/{order_reference}/tickets', [
    'as'   => 'showOrderTickets',
    'uses' => 'EventCheckoutController@showOrderTickets',
]);

/*
 * Backend routes
 */
Route::group(['middleware' => ['auth', 'first.run']], function () {

    /*
     * Edit User
     */
     Route::group(['prefix' => 'user'], function () {

         Route::get('/', [
            'as'   => 'showEditUser',
            'uses' => 'UserController@showEditUser',
        ]);
         Route::post('/', [
            'as'   => 'postEditUser',
            'uses' => 'UserController@postEditUser',
        ]);

     });

    /*
     * Manage account
     */
    Route::group(['prefix' => 'account'], function () {

        Route::get('/', [
            'as'   => 'showEditAccount',
            'uses' => 'ManageAccountController@showEditAccount',
        ]);

        Route::post('/', [
            'as'   => 'postEditAccount',
            'uses' => 'ManageAccountController@postEditAccount',
        ]);
        Route::post('/edit_payment', [
            'as'   => 'postEditAccountPayment',
            'uses' => 'ManageAccountController@postEditAccountPayment',
        ]);

        Route::post('invite_user', [
            'as'   => 'postInviteUser',
            'uses' => 'ManageAccountController@postInviteUser',
        ]);

    });

    Route::get('select_organiser', [
       'as'   => 'showSelectOrganiser',
       'uses' => 'OrganiserController@showSelectOragniser',
    ]);

    /*
     * Organiser routes
     */
    Route::group(['prefix' => 'organiser'], function () {

        Route::get('{organiser_id}/dashboard', [
            'as'   => 'showOrganiserDashboard',
            'uses' => 'OrganiserDashboardController@showDashboard',
        ]);
        Route::get('{organiser_id}/events', [
            'as'   => 'showOrganiserEvents',
            'uses' => 'OrganiserEventsController@showEvents',
        ]);
        Route::get('{organiser_id}/customize', [
            'as'   => 'showOrganiserCustomize',
            'uses' => 'OrganiserCustomizeController@showCustomize',
        ]);
        Route::get('create', [
            'as'   => 'showCreateOrganiser',
            'uses' => 'OrganiserController@showCreateOrganiser',
        ]);
        Route::post('create', [
            'as'   => 'postCreateOrganiser',
            'uses' => 'OrganiserController@postCreateOrganiser',
        ]);
        Route::get('{organiser_id}/edit', [
            'as'   => 'showEditOrganiser',
            'uses' => 'OrganiserController@showEditOrganiser',
        ]);
        Route::post('{organiser_id}/edit', [
            'as'   => 'postEditOrganiser',
            'uses' => 'OrganiserCustomizeController@postEditOrganiser',
        ]);

        Route::post('{organiser_id}/page_design', [
            'as'   => 'postEditOrganiserPageDesign',
            'uses' => 'OrganiserCustomizeController@postEditOrganiserPageDesign'
        ]);
    });

    /*
     * Events dashboard
     */
    Route::group(['prefix' => 'events'], function () {

        /*
         * ----------
         * Create Event
         * ----------
         */
        Route::get('/create', [
            'as'   => 'showCreateEvent',
            'uses' => 'EventController@showCreateEvent',
        ]);

        Route::post('/create', [
            'as'   => 'postCreateEvent',
            'uses' => 'EventController@postCreateEvent',
        ]);
    });

    /*
     * Upload event images
     */
    Route::post('/upload_image', [
        'as'   => 'postUploadEventImage',
        'uses' => 'EventController@postUploadEventImage',
    ]);

    /*
     * Event management routes
     */
    Route::group(['prefix' => 'event'], function () {

        /*
         * Dashboard
         */
        Route::get('{event_id}/dashboard/', [
            'as'   => 'showEventDashboard',
            'uses' => 'EventDashboardController@showDashboard', ]
        );

        Route::get('{event_id}', function ($event_id) {
            return Redirect::route('showEventDashboard', [
                        'event_id' => $event_id,
            ]);
        });

        /*
         * @todo Move to a controller
         */
        Route::get('{event_id}/go_live', ['as' => 'MakeEventLive', function ($event_id) {
            $event = \App\Models\Event::scope()->findOrFail($event_id);
            $event->is_live = 1;
            $event->save();
            \Session::flash('message', 'Event Successfully Made Live! You can undo this action in event settings page.');

            return Redirect::route('showEventDashboard', [
                'event_id' => $event_id,
            ]);
        }]);

        /*
         * -------
         * Tickets
         * -------
         */
        Route::get('{event_id}/tickets/', [
            'as'   => 'showEventTickets',
            'uses' => 'EventTicketsController@showTickets',
        ]);
        Route::get('{event_id}/tickets/edit/{ticket_id}', [
            'as'   => 'showEditTicket',
            'uses' => 'EventTicketsController@showEditTicket',
        ]);
        Route::post('{event_id}/tickets/edit/{ticket_id}', [
            'as'   => 'postEditTicket',
            'uses' => 'EventTicketsController@postEditTicket',
        ]);
        Route::get('{event_id}/tickets/create', [
            'as'   => 'showCreateTicket',
            'uses' => 'EventTicketsController@showCreateTicket',
        ]);
        Route::post('{event_id}/tickets/create', [
            'as'   => 'postCreateTicket',
            'uses' => 'EventTicketsController@postCreateTicket',
        ]);
        Route::post('{event_id}/tickets/delete', [
            'as'   => 'postDeleteTicket',
            'uses' => 'EventTicketsController@postDeleteTicket',
        ]);
        Route::post('{event_id}/tickets/pause', [
            'as'   => 'postPauseTicket',
            'uses' => 'EventTicketsController@postPauseTicket',
        ]);

        /*
         * Ticket questions
         */
        Route::get('{event_id}/tickets/questions', [
            'as'   => 'showTicketQuestions',

app/Models/Event.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Str;
use URL;

class Event extends MyBaseModel
{
    use SoftDeletes;
    
    /**
     * The validation rules.
     *
     * @var array $rules
     */
    protected $rules = [
        'title'               => ['required'],
        'description'         => ['required'],
        'location_venue_name' => ['required_without:venue_name_full'],
        'venue_name_full'     => ['required_without:location_venue_name'],
        'start_date'          => ['required'],
        'end_date'            => ['required'],
        'organiser_name'      => ['required_without:organiser_id'],
        'event_image'         => ['mimes:jpeg,jpg,png', 'max:3000'],
    ];

    /**
     * The validation error messages.
     *
     * @var array $messages
     */
    protected $messages = [
        'title.required'                       => 'You must at least give a title for your event.',
        'organiser_name.required_without'      => 'Please create an organiser or select an existing organiser.',
        'event_image.mimes'                    => 'Please ensure you are uploading an image (JPG, PNG, JPEG)',
        'event_image.max'                      => 'Pleae ensure the image is not larger then 3MB',
        'location_venue_name.required_without' => 'Please enter a venue for your event',
        'venue_name_full.required_without'     => 'Please enter a venue for your event',
    ];

    /**
     * The questions associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions()
    {
        return $this->belongsToMany('\App\Models\Question', 'event_question');
    }

    /**
     * The questions associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions_with_tashed()
    {
        return $this->belongsToMany('\App\Models\Question', 'event_question')->withTrashed();
    }

    /**
     * The attendees associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attendees()
    {
        return $this->hasMany('\App\Models\Attendee');
    }

    /**
     * The images associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany('\App\Models\EventImage');
    }

    /**
     * The messages associated with the event.
     *
     * @return mixed
     */
    public function messages()
    {
        return $this->hasMany('\App\Models\Message')->orderBy('created_at', 'DESC');
    }

    /**
     * The tickets associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tickets()
    {
        return $this->hasMany('\App\Models\Ticket');
    }

    /**
     * The stats associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function stats()
    {
        return $this->hasMany('\App\Models\EventStats');
    }

    /**
     * The affiliates associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function affiliates()
    {
        return $this->hasMany('\App\Models\Affiliate');
    }

    /**
     * The orders associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders()
    {
        return $this->hasMany('\App\Models\Order');
    }

    /**
     * The account associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function account()
    {
        return $this->belongsTo('\App\Models\Account');
    }

    /**
     * The currency associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function currency()
    {
        return $this->belongsTo('\App\Models\Currency');
    }

    /**
     * The organizer associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function organiser()
    {
        return $this->belongsTo('\App\Models\Organiser');
    }

    /**
     * Get the embed url.
     *
     * @return mixed
     */
    public function getEmbedUrlAttribute()
    {
        return str_replace(['http:', 'https:'], '', route('showEmbeddedEventPage', ['event' => $this->id]));
    }

    /**
     * Get the fixed fee.
     *
     * @return mixed
     */
    public function getFixedFeeAttribute()
    {
        return config('attendize.ticket_booking_fee_fixed') + $this->organiser_fee_fixed;
    }

    /**
     * Get the percentage fee.
     *
     * @return mixed
     */
    public function getPercentageFeeAttribute()
    {
        return config('attendize.ticket_booking_fee_percentage') + $this->organiser_fee_percentage;
    }

    /**
     * Indicates whether the event is currently happening.
     *
     * @return bool
     */
    public function getHappeningNowAttribute()
    {
        return Carbon::now()->between($this->start_date, $this->end_date);
    }

    /**
     * Get the currency sybol.
     *
     * @return \Illuminate\Support\Collection
     */
    public function getCurrencySymbolAttribute()
    {
        return $this->currency->symbol_left;
    }

    /**
     * Get the currency code.
     *
     * @return \Illuminate\Support\Collection
     */
    public function getCurrencyCodeAttribute()
    {
        return $this->currency->code;
    }

    /**
     * Get the embed html code.
     *
     * @return string
     */
    public function getEmbedHtmlCodeAttribute()
    {
        return "<!--Attendize.com Ticketing Embed Code-->
                <iframe style='overflow:hidden; min-height: 350px;' frameBorder='0' seamless='seamless' width='100%' height='100%' src='".$this->embed_url."' vspace='0' hspace='0' scrolling='auto' allowtransparency='true'></iframe>
                <!--/Attendize.com Ticketing Embed Code-->";
    }

    /**
     * Get a usable address for embedding Google Maps
     *
     */
    public function getMapAddressAttribute()
    {
        $string = $this->venue.','
                .$this->location_street_number.','
                .$this->location_address_line_1.','
                .$this->location_address_line_2.','
                .$this->location_state.','
                .$this->location_post_code.','
                .$this->location_country;

        return urlencode($string);
    }

    /**
     * Get the big image url.
     *
     * @return string
     */
    public function getBgImageUrlAttribute()
    {
        return URL::to('/').'/'.$this->bg_image_path;
    }

    /**
     * Get the url of the event.
     *
     * @return string
     */
    public function getEventUrlAttribute()
    {
        return URL::to('/').'/e/'.$this->id.'/'.Str::slug($this->title);
    }

    /**
     * Get the sales and fees volume.
     *
     * @return \Illuminate\Support\Collection|mixed|static
     */
    public function getSalesAndFeesVoulmeAttribute()
    {
        return $this->sales_volume + $this->organiser_fees_volume;
    }

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array $dates
     */
    public function getDates()
    {
        return ['created_at', 'updated_at', 'start_date', 'end_date'];
    }
}

resources/views/ManageOrganiser/Partials/EventCreateAndEditJS.blade.php
{!! HTML::script('vendor/simplemde/dist/simplemde.min.js') !!}
{!! HTML::style('vendor/simplemde/dist/simplemde.min.css') !!}

<script>
    $(function() {
        try {
            $(".geocomplete").geocomplete({
                    details: "form.gf",
                    types: ["geocode", "establishment"]
                }).bind("geocode:result", function(event, result) {
                    console.log(result);
            }, 1000);

        } catch (e) {
            console.log(e);
        }

        var simplemde = new SimpleMDE({
            element: $(".ediatble")[0],
            spellChecker: false,
            status: false
        });
        $("#DatePicker").remove();
        var $div = $("<div>", {id: "DatePicker"});
        $("body").append($div);
        $div.DateTimePicker({
            dateTimeFormat: window.Attendize.DateTimeFormat
        });

    });
</script>
<style>
    .editor-toolbar {
        border-radius: 0 !important;
    }
    .CodeMirror, .CodeMirror-scroll {
        min-height: 100px !important;
    }

    .create_organiser, .address-manual {
        padding: 10px;
        border: 1px solid #ddd;
        margin-top: 10px;
        margin-bottom: 10px;
        background-color: #FAFAFA;
    }

    .in-form-link {
        display: block; padding: 5px;margin-bottom: 5px;padding-left: 0;
    }
</style>

resources/views/ManageOrganiser/Partials/EventPanel.blade.php
<div class="panel panel-success event">
    <div class="panel-heading" data-style="background-color: {{{$event->bg_color}}};background-image: url({{{$event->bg_image_url}}}); background-size: cover;">
        <div class="event-date">
            <div class="month">
                {{strtoupper($event->start_date->format('M'))}}
            </div>
            <div class="day">
                {{$event->start_date->format('d')}}
            </div>
        </div>
        <ul class="event-meta">
            <li class="event-title">
                <a title="{{{$event->title}}}" href="{{route('showEventDashboard', ['event_id'=>$event->id])}}">
                    {{{ str_limit($event->title, $limit = 75, $end = '...') }}}
                </a>
            </li>
            <li class="event-organiser">
                By <a href='{{route('showOrganiserDashboard', ['organiser_id' => $event->organiser->id])}}'>{{{$event->organiser->name}}}</a>
            </li>
        </ul>

    </div>

    <div class="panel-body">
        <ul class="nav nav-section nav-justified mt5 mb5">
            <li>
                <div class="section">
                    <h4 class="nm">{{$event->tickets->sum('quantity_sold')}}</h4>
                    <p class="nm text-muted">Tickets Sold</p>
                </div>
            </li>

            <li>
                <div class="section">
                    <h4 class="nm">{{{money($event->sales_volume + $event->organiser_fees_volume, $event->currency->code)}}}</h4>
                    <p class="nm text-muted">Revenue</p>
                </div>
            </li>
        </ul>
    </div>
    <div class="panel-footer">
        <ul class="nav nav-section nav-justified">
            <li>
                <a href="{{route('showEventCustomize', ['event_id' => $event->id])}}">
                    <i class="ico-edit"></i> Edit
                </a>
            </li>

            <li>
                <a href="{{route('showEventDashboard', ['event_id' => $event->id])}}">
                    <i class="ico-cog"></i> Manage
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/ManageOrganiser/Partials/EventsBlankSlate.blade.php
@extends('Shared.Layouts.BlankSlate')

@section('blankslate-icon-class')
    ico-ticket
@stop

@section('blankslate-title')
    No Events Yet!
@stop

@section('blankslate-text')
    Looks like you have yet to create an event. You can create one by clicking the button below.
@stop

@section('blankslate-body')
<button data-invoke="modal" data-modal-id="CreateEvent" data-href="{{route('showCreateEvent', ['organiser_id' => $organiser->id])}}" href='javascript:void(0);'  class="btn btn-success mt5 btn-lg" type="button">
    <i class="ico-ticket"></i>
    Create Event
</button>
@stop

resources/views/ManageOrganiser/Partials/Sidebar.blade.php
<aside class="sidebar sidebar-left sidebar-menu">
    <section class="content">
        <h5 class="heading">Organiser Menu</h5>

        <ul id="nav" class="topmenu">
            <li class="{{ Request::is('*dashboard*') ? 'active' : '' }}">
                <a href="{{route('showOrganiserDashboard', array('organiser_id' => $organiser->id))}}">
                    <span class="figure"><i class="ico-home2"></i></span>
                    <span class="text">Dashboard</span>
                </a>
            </li>
            <li class="{{ Request::is('*events*') ? 'active' : '' }}">
                <a href="{{route('showOrganiserEvents', array('organiser_id' => $organiser->id))}}">
                    <span class="figure"><i class="ico-calendar"></i></span>
                    <span class="text">Events</span>
                </a>
            </li>

            <li class="{{ Request::is('*customize*') ? 'active' : '' }}">
                <a href="{{route('showOrganiserCustomize', array('organiser_id' => $organiser->id))}}">
                    <span class="figure"><i class="ico-cog"></i></span>
                    <span class="text">Customize</span>
                </a>
            </li>
        </ul>
    </section>
</aside>

resources/views/ManageOrganiser/Partials/TopNav.blade.php
<ul class="nav navbar-nav navbar-left">
    <!-- Show Side Menu -->
    <li class="navbar-main">
        <a href="javascript:void(0);" class="toggleSidebar" title="Show sidebar">
            <span class="toggleMenuIcon">
                <span class="icon ico-menu"></span>
            </span>
        </a>
    </li>
    <!--/ Show Side Menu -->
    <li class="nav-button ">
        <a target="_blank" href="{{ route('showOrganiserHome',[$organiser->id]) }}">
            <span>
                <i class="ico-eye2"></i>&nbsp;Organiser Page
            </span>
        </a>
    </li>
</ul>