app/Http/routes.php
<?php

/*
 * Include our API routes file
 */
include_once('api_routes.php');

/*
 * -------------------------
 * Installer
 * -------------------------
 */
Route::get('install', [
    'as'   => 'showInstaller',
    'uses' => 'InstallerController@showInstaller',
]);
Route::post('install', [
    'as'   => 'postInstaller',
    'uses' => 'InstallerController@postInstaller',
]);

/*
 * Stripe connect return
 */
Route::any('payment/return/stripe', [
    'as'   => 'showStripeReturn',
    'uses' => 'ManageAccountController@showStripeReturn',
]);

/*
 * Logout
 */
Route::any('/logout', [
    'uses' => 'UserLogoutController@doLogout',
    'as'   => 'logout',
]);

Route::group(['middleware' => ['installed']], function () {

    /*
     * Login
     */
    Route::get('/login', [
        'as'   => 'login',
        'uses' => 'UserLoginController@showLogin',
    ]);
    Route::post('/login', 'UserLoginController@postLogin');

    /*
     * Forgot password
     */
    Route::get('login/forgot-password', [
        'as'   => 'forgotPassword',
        'uses' => 'RemindersController@getRemind',
    ]);

    Route::post('login/forgot-password', [
        'as'   => 'postForgotPassword',
        'uses' => 'RemindersController@postRemind',
    ]);

    /*
     * Reset Password
     */
    Route::get('login/reset-password/{token}', [
        'as'   => 'showResetPassword',
        'uses' => 'RemindersController@getReset',
    ]);

    Route::post('login/reset-password', [
        'as'   => 'postResetPassword',
        'uses' => 'RemindersController@postReset',
    ]);

    /*
     * Registration / Account creation
     */
    Route::get('/signup', [
        'uses' => 'UserSignupController@showSignup',
        'as'   => 'showSignup',
    ]);
    Route::post('/signup', 'UserSignupController@postSignup');

    /*
     * Confirm Email
     */
    Route::get('signup/confirm_email/{confirmation_code}', [
        'as'   => 'confirmEmail',
        'uses' => 'UserSignupController@confirmEmail',
    ]);
});

/*
 * Public organiser page routes
 */
Route::group(['prefix' => 'o'], function () {

    Route::get('/{organiser_id}/{organier_slug?}', [
        'as'   => 'showOrganiserHome',
        'uses' => 'OrganiserViewController@showOrganiserHome',
    ]);

});

/*
 * Public event page routes
 */
Route::group(['prefix' => 'e'], function () {

    /*
     * Embedded events
     */
    Route::get('/{event_id}/embed', [
        'as'   => 'showEmbeddedEventPage',
        'uses' => 'EventViewEmbeddedController@showEmbeddedEvent',
    ]);

    Route::get('/{event_id}/{event_slug?}', [
        'as'   => 'showEventPage',
        'uses' => 'EventViewController@showEventHome',
    ]);

    Route::post('/{event_id}/contact_organiser', [
       'as'    => 'postContactOrganiser',
        'uses' => 'EventViewController@postContactOrganiser',
    ]);

    /*
     * Used for previewing designs in the backend. Doesn't log page views etc.
     */
    Route::get('/{event_id}/preview', [
        'as'   => 'showEventPagePreview',
        'uses' => 'EventViewController@showEventHomePreview',
    ]);

    Route::post('{event_id}/checkout/', [
        'as'   => 'postValidateTickets',
        'uses' => 'EventCheckoutController@postValidateTickets',
    ]);

    Route::get('{event_id}/checkout/create', [
        'as'   => 'showEventCheckout',
        'uses' => 'EventCheckoutController@showEventCheckout',
    ]);

    Route::get('{event_id}/checkout/success', [
        'as'   => 'showEventCheckoutPaymentReturn',
        'uses' => 'EventCheckoutController@showEventCheckoutPaymentReturn',
    ]);



    Route::post('{event_id}/checkout/create', [
        'as'   => 'postCreateOrder',
        'uses' => 'EventCheckoutController@postCreateOrder',
    ]);
});

/*
 * Public view order routes
 */
Route::get('order/{order_reference}', [
    'as'   => 'showOrderDetails',
    'uses' => 'EventCheckoutController@showOrderDetails',
]);

Route::get('order/{order_reference}/tickets', [
    'as'   => 'showOrderTickets',
    'uses' => 'EventCheckoutController@showOrderTickets',
]);

/*
 * Backend routes
 */
Route::group(['middleware' => ['auth', 'first.run']], function () {

    /*
     * Edit User
     */
     Route::group(['prefix' => 'user'], function () {

         Route::get('/', [
            'as'   => 'showEditUser',
            'uses' => 'UserController@showEditUser',
        ]);
         Route::post('/', [
            'as'   => 'postEditUser',
            'uses' => 'UserController@postEditUser',
        ]);

     });

    /*
     * Manage account
     */
    Route::group(['prefix' => 'account'], function () {

        Route::get('/', [
            'as'   => 'showEditAccount',
            'uses' => 'ManageAccountController@showEditAccount',
        ]);

        Route::post('/', [
            'as'   => 'postEditAccount',
            'uses' => 'ManageAccountController@postEditAccount',
        ]);
        Route::post('/edit_payment', [
            'as'   => 'postEditAccountPayment',
            'uses' => 'ManageAccountController@postEditAccountPayment',
        ]);

        Route::post('invite_user', [
            'as'   => 'postInviteUser',
            'uses' => 'ManageAccountController@postInviteUser',
        ]);

    });

    Route::get('select_organiser', [
       'as'   => 'showSelectOrganiser',
       'uses' => 'OrganiserController@showSelectOragniser',
    ]);

    /*
     * Organiser routes
     */
    Route::group(['prefix' => 'organiser'], function () {

        Route::get('{organiser_id}/dashboard', [
            'as'   => 'showOrganiserDashboard',
            'uses' => 'OrganiserDashboardController@showDashboard',
        ]);
        Route::get('{organiser_id}/events', [
            'as'   => 'showOrganiserEvents',
            'uses' => 'OrganiserEventsController@showEvents',
        ]);
        Route::get('{organiser_id}/customize', [
            'as'   => 'showOrganiserCustomize',
            'uses' => 'OrganiserCustomizeController@showCustomize',
        ]);
        Route::get('create', [
            'as'   => 'showCreateOrganiser',
            'uses' => 'OrganiserController@showCreateOrganiser',
        ]);
        Route::post('create', [
            'as'   => 'postCreateOrganiser',
            'uses' => 'OrganiserController@postCreateOrganiser',
        ]);
        Route::get('{organiser_id}/edit', [
            'as'   => 'showEditOrganiser',
            'uses' => 'OrganiserController@showEditOrganiser',
        ]);
        Route::post('{organiser_id}/edit', [
            'as'   => 'postEditOrganiser',
            'uses' => 'OrganiserCustomizeController@postEditOrganiser',
        ]);

        Route::post('{organiser_id}/page_design', [
            'as'   => 'postEditOrganiserPageDesign',
            'uses' => 'OrganiserCustomizeController@postEditOrganiserPageDesign'
        ]);
    });

    /*
     * Events dashboard
     */
    Route::group(['prefix' => 'events'], function () {

        /*
         * ----------
         * Create Event
         * ----------
         */
        Route::get('/create', [
            'as'   => 'showCreateEvent',
            'uses' => 'EventController@showCreateEvent',
        ]);

        Route::post('/create', [
            'as'   => 'postCreateEvent',
            'uses' => 'EventController@postCreateEvent',
        ]);
    });

    /*
     * Upload event images
     */
    Route::post('/upload_image', [
        'as'   => 'postUploadEventImage',
        'uses' => 'EventController@postUploadEventImage',
    ]);

    /*
     * Event management routes
     */
    Route::group(['prefix' => 'event'], function () {

        /*
         * Dashboard
         */
        Route::get('{event_id}/dashboard/', [
            'as'   => 'showEventDashboard',
            'uses' => 'EventDashboardController@showDashboard', ]
        );

        Route::get('{event_id}', function ($event_id) {
            return Redirect::route('showEventDashboard', [
                        'event_id' => $event_id,
            ]);
        });

        /*
         * @todo Move to a controller
         */
        Route::get('{event_id}/go_live', ['as' => 'MakeEventLive', function ($event_id) {
            $event = \App\Models\Event::scope()->findOrFail($event_id);
            $event->is_live = 1;
            $event->save();
            \Session::flash('message', 'Event Successfully Made Live! You can undo this action in event settings page.');

            return Redirect::route('showEventDashboard', [
                'event_id' => $event_id,
            ]);
        }]);

        /*
         * -------
         * Tickets
         * -------
         */
        Route::get('{event_id}/tickets/', [
            'as'   => 'showEventTickets',
            'uses' => 'EventTicketsController@showTickets',
        ]);
        Route::get('{event_id}/tickets/edit/{ticket_id}', [
            'as'   => 'showEditTicket',
            'uses' => 'EventTicketsController@showEditTicket',
        ]);
        Route::post('{event_id}/tickets/edit/{ticket_id}', [
            'as'   => 'postEditTicket',
            'uses' => 'EventTicketsController@postEditTicket',
        ]);
        Route::get('{event_id}/tickets/create', [
            'as'   => 'showCreateTicket',
            'uses' => 'EventTicketsController@showCreateTicket',
        ]);
        Route::post('{event_id}/tickets/create', [
            'as'   => 'postCreateTicket',
            'uses' => 'EventTicketsController@postCreateTicket',
        ]);
        Route::post('{event_id}/tickets/delete', [
            'as'   => 'postDeleteTicket',
            'uses' => 'EventTicketsController@postDeleteTicket',
        ]);
        Route::post('{event_id}/tickets/pause', [
            'as'   => 'postPauseTicket',
            'uses' => 'EventTicketsController@postPauseTicket',
        ]);

        /*
         * Ticket questions
         */
        Route::get('{event_id}/tickets/questions', [
            'as'   => 'showTicketQuestions',

app/Models/Event.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Str;
use URL;

class Event extends MyBaseModel
{
    use SoftDeletes;
    
    /**
     * The validation rules.
     *
     * @var array $rules
     */
    protected $rules = [
        'title'               => ['required'],
        'description'         => ['required'],
        'location_venue_name' => ['required_without:venue_name_full'],
        'venue_name_full'     => ['required_without:location_venue_name'],
        'start_date'          => ['required'],
        'end_date'            => ['required'],
        'organiser_name'      => ['required_without:organiser_id'],
        'event_image'         => ['mimes:jpeg,jpg,png', 'max:3000'],
    ];

    /**
     * The validation error messages.
     *
     * @var array $messages
     */
    protected $messages = [
        'title.required'                       => 'You must at least give a title for your event.',
        'organiser_name.required_without'      => 'Please create an organiser or select an existing organiser.',
        'event_image.mimes'                    => 'Please ensure you are uploading an image (JPG, PNG, JPEG)',
        'event_image.max'                      => 'Pleae ensure the image is not larger then 3MB',
        'location_venue_name.required_without' => 'Please enter a venue for your event',
        'venue_name_full.required_without'     => 'Please enter a venue for your event',
    ];

    /**
     * The questions associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions()
    {
        return $this->belongsToMany('\App\Models\Question', 'event_question');
    }

    /**
     * The questions associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions_with_tashed()
    {
        return $this->belongsToMany('\App\Models\Question', 'event_question')->withTrashed();
    }

    /**
     * The attendees associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attendees()
    {
        return $this->hasMany('\App\Models\Attendee');
    }

    /**
     * The images associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany('\App\Models\EventImage');
    }

    /**
     * The messages associated with the event.
     *
     * @return mixed
     */
    public function messages()
    {
        return $this->hasMany('\App\Models\Message')->orderBy('created_at', 'DESC');
    }

    /**
     * The tickets associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tickets()
    {
        return $this->hasMany('\App\Models\Ticket');
    }

    /**
     * The stats associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function stats()
    {
        return $this->hasMany('\App\Models\EventStats');
    }

    /**
     * The affiliates associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function affiliates()
    {
        return $this->hasMany('\App\Models\Affiliate');
    }

    /**
     * The orders associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders()
    {
        return $this->hasMany('\App\Models\Order');
    }

    /**
     * The account associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function account()
    {
        return $this->belongsTo('\App\Models\Account');
    }

    /**
     * The currency associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function currency()
    {
        return $this->belongsTo('\App\Models\Currency');
    }

    /**
     * The organizer associated with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function organiser()
    {
        return $this->belongsTo('\App\Models\Organiser');
    }

    /**
     * Get the embed url.
     *
     * @return mixed
     */
    public function getEmbedUrlAttribute()
    {
        return str_replace(['http:', 'https:'], '', route('showEmbeddedEventPage', ['event' => $this->id]));
    }

    /**
     * Get the fixed fee.
     *
     * @return mixed
     */
    public function getFixedFeeAttribute()
    {
        return config('attendize.ticket_booking_fee_fixed') + $this->organiser_fee_fixed;
    }

    /**
     * Get the percentage fee.
     *
     * @return mixed
     */
    public function getPercentageFeeAttribute()
    {
        return config('attendize.ticket_booking_fee_percentage') + $this->organiser_fee_percentage;
    }

    /**
     * Indicates whether the event is currently happening.
     *
     * @return bool
     */
    public function getHappeningNowAttribute()
    {
        return Carbon::now()->between($this->start_date, $this->end_date);
    }

    /**
     * Get the currency sybol.
     *
     * @return \Illuminate\Support\Collection
     */
    public function getCurrencySymbolAttribute()
    {
        return $this->currency->symbol_left;
    }

    /**
     * Get the currency code.
     *
     * @return \Illuminate\Support\Collection
     */
    public function getCurrencyCodeAttribute()
    {
        return $this->currency->code;
    }

    /**
     * Get the embed html code.
     *
     * @return string
     */
    public function getEmbedHtmlCodeAttribute()
    {
        return "<!--Attendize.com Ticketing Embed Code-->
                <iframe style='overflow:hidden; min-height: 350px;' frameBorder='0' seamless='seamless' width='100%' height='100%' src='".$this->embed_url."' vspace='0' hspace='0' scrolling='auto' allowtransparency='true'></iframe>
                <!--/Attendize.com Ticketing Embed Code-->";
    }

    /**
     * Get a usable address for embedding Google Maps
     *
     */
    public function getMapAddressAttribute()
    {
        $string = $this->venue.','
                .$this->location_street_number.','
                .$this->location_address_line_1.','
                .$this->location_address_line_2.','
                .$this->location_state.','
                .$this->location_post_code.','
                .$this->location_country;

        return urlencode($string);
    }

    /**
     * Get the big image url.
     *
     * @return string
     */
    public function getBgImageUrlAttribute()
    {
        return URL::to('/').'/'.$this->bg_image_path;
    }

    /**
     * Get the url of the event.
     *
     * @return string
     */
    public function getEventUrlAttribute()
    {
        return URL::to('/').'/e/'.$this->id.'/'.Str::slug($this->title);
    }

    /**
     * Get the sales and fees volume.
     *
     * @return \Illuminate\Support\Collection|mixed|static
     */
    public function getSalesAndFeesVoulmeAttribute()
    {
        return $this->sales_volume + $this->organiser_fees_volume;
    }

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array $dates
     */
    public function getDates()
    {
        return ['created_at', 'updated_at', 'start_date', 'end_date'];
    }
}

resources/views/ManageEvent/Partials/AttendeesBlankSlate.blade.php
@extends('Shared.Layouts.BlankSlate')


@section('blankslate-icon-class')
    ico-users
@stop

@section('blankslate-title')
    No Attendees Yet
@stop

@section('blankslate-text')
    Attendees will appear here once they successfully registered for your event, or, you can manually add attendees yourself.
@stop

@section('blankslate-body')
<button data-invoke="modal" data-modal-id='CreateTicket' data-href="{{route('showCreateAttendee', array('event_id'=>$event->id))}}" href='javascript:void(0);'  class=' btn btn-success mt5 btn-lg' type="button" >
    <i class="ico-ticket"></i>
    Create Attendee
</button>
@stop

resources/views/ManageEvent/Partials/EditEventForm.blade.php
@include('ManageOrganiser.Partials.EventCreateAndEditJS')

{!! Form::model($event, array('url' => route('postEditEvent', ['event_id' => $event->id]), 'class' => 'ajax gf')) !!}

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            {!! Form::label('is_live', 'Event Visibility', array('class'=>'control-label required')) !!}
            {!!  Form::select('is_live', [
            '1' => 'Make event visible to the public.',
            '0' => 'Hide event from the public.'],null,
                                        array(
                                        'class'=>'form-control'
                                        ))  !!}
        </div>
        <div class="form-group">
            {!! Form::label('title', 'Event Title', array('class'=>'control-label required')) !!}
            {!!  Form::text('title', Input::old('title'),
                                        array(
                                        'class'=>'form-control',
                                        'placeholder'=>'E.g: '.Auth::user()->first_name.'\'s Interational Conference'
                                        ))  !!}
        </div>

        <div class="form-group">
           {!! Form::label('description', 'Event Description', array('class'=>'control-label')) !!}
            {!!  Form::textarea('description', Input::old('description'),
                                        array(
                                        'class'=>'form-control editable',
                                        'rows' => 5
                                        ))  !!}
        </div>

        <div class="form-group address-automatic" style="display:{{$event->location_is_manual ? 'none' : 'block'}};">
            {!! Form::label('name', 'Venue Name', array('class'=>'control-label required ')) !!}
            {!!  Form::text('venue_name_full', Input::old('venue_name_full'),
                                        array(
                                        'class'=>'form-control geocomplete location_field',
                                        'placeholder'=>'E.g: The Crab Shack'
                                        ))  !!}

            <!--These are populated with the Google places info-->
            <div>
               {!! Form::hidden('formatted_address', $event->location_address, ['class' => 'location_field']) !!}
               {!! Form::hidden('street_number', $event->location_street_number, ['class' => 'location_field']) !!}
               {!! Form::hidden('country', $event->location_country, ['class' => 'location_field']) !!}
               {!! Form::hidden('country_short', $event->location_country_short, ['class' => 'location_field']) !!}
               {!! Form::hidden('place_id', $event->location_google_place_id, ['class' => 'location_field']) !!}
               {!! Form::hidden('name', $event->venue_name, ['class' => 'location_field']) !!}
               {!! Form::hidden('location', '', ['class' => 'location_field']) !!}
               {!! Form::hidden('postal_code', $event->location_post_code, ['class' => 'location_field']) !!}
               {!! Form::hidden('route', $event->location_address_line_1, ['class' => 'location_field']) !!}
               {!! Form::hidden('lat', $event->location_lat, ['class' => 'location_field']) !!}
               {!! Form::hidden('lng', $event->location_long, ['class' => 'location_field']) !!}
               {!! Form::hidden('administrative_area_level_1', $event->location_state, ['class' => 'location_field']) !!}
               {!! Form::hidden('sublocality', '', ['class' => 'location_field']) !!}
               {!! Form::hidden('locality', $event->location_address_line_1, ['class' => 'location_field']) !!}
            </div>
            <!-- /These are populated with the Google places info-->

        </div>

        <div class="address-manual" style="display:{{$event->location_is_manual ? 'block' : 'none'}};">
            <div class="form-group">
                {!! Form::label('location_venue_name', 'Venue Name', array('class'=>'control-label required ')) !!}
                {!!  Form::text('location_venue_name', $event->venue_name, [
                                        'class'=>'form-control location_field',
                                        'placeholder'=>'E.g: The Crab Shack'
                            ])  !!}
            </div>
            <div class="form-group">
                {!! Form::label('location_address_line_1', 'Address Line 1', array('class'=>'control-label')) !!}
                {!!  Form::text('location_address_line_1', $event->location_address_line_1, [
                                        'class'=>'form-control location_field',
                                        'placeholder'=>'E.g: 45 Grafton St.'
                            ])  !!}
            </div>
            <div class="form-group">
                {!! Form::label('location_address_line_2', 'Address Line 2', array('class'=>'control-label')) !!}
                {!!  Form::text('location_address_line_2', $event->location_address_line_2, [
                                        'class'=>'form-control location_field',
                                        'placeholder'=>'E.g: Dublin.'
                            ])  !!}
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('location_state', 'City', array('class'=>'control-label')) !!}
                        {!!  Form::text('location_state', $event->location_state, [
                                        'class'=>'form-control location_field',
                                        'placeholder'=>'E.g: Dublin.'
                            ])  !!}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('location_post_code', 'Post Code', array('class'=>'control-label')) !!}
                        {!!  Form::text('location_post_code', $event->location_post_code, [
                                        'class'=>'form-control location_field',
                                        'placeholder'=>'E.g: Dublin.'
                            ])  !!}
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix" style="margin-top:-10px; padding: 5px; padding-top: 0px;">
            <span class="pull-right">
                or <a data-clear-field=".location_field" data-toggle-class=".address-automatic, .address-manual" data-show-less-text="{{$event->location_is_manual ? 'Enter Address Manually' : 'Select From Existing Venues'}}" href="javascript:void(0);" class="show-more-options clear_location">{{$event->location_is_manual ? 'Select From Existing Venues' : 'Enter Address Manually'}}</a>
            </span>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    {!! Form::label('start_date', 'Event Start Date', array('class'=>'required control-label')) !!}
                    {!!  Form::text('start_date', $event->getFormatedDate('start_date'),
                                                        [
                                                    'class'=>'form-control start hasDatepicker ',
                                                    'data-field'=>'datetime',
                                                    'data-startend'=>'start',
                                                    'data-startendelem'=>'.end',
                                                    'readonly'=>''

                                                ])  !!}
                </div>
            </div>

            <div class="col-sm-6 ">
                <div class="form-group">
                    {!!  Form::label('end_date', 'Event End Date',
                                        [
                                    'class'=>'required control-label '
                                ])  !!}
                    {!!  Form::text('end_date', $event->getFormatedDate('end_date'),
                                                [
                                            'class'=>'form-control end hasDatepicker ',
                                            'data-field'=>'datetime',
                                            'data-startend'=>'end',
                                            'data-startendelem'=>'.start',
                                            'readonly'=>''
                                        ])  !!}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                   {!! Form::label('event_image', 'Event Flyer', array('class'=>'control-label ')) !!}
                   {!! Form::styledFile('event_image', 1) !!}
                </div>
            </div>
            <div class="col-md-6">
                <div class="float-l">
                    @if($event->images->count())
                    {!! Form::label('', 'Current Event Flyer', array('class'=>'control-label ')) !!}
                    <div class="form-group">
                        <div class="well well-sm well-small">
                           {!! Form::label('remove_current_image', 'Delete?', array('class'=>'control-label ')) !!}
                           {!! Form::checkbox('remove_current_image') !!}

                        </div>
                    </div>
                    <div class="thumbnail">
                       {!!HTML::image('/'.$event->images->first()['image_path'])!!}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel-footer mt15 text-right">
           {!! Form::hidden('organiser_id', $event->organiser_id) !!}
           {!! Form::submit('Save Changes', ['class'=>"btn btn-success"]) !!}
        </div>
    </div>
    {!! Form::close() !!}
</div>

resources/views/ManageEvent/Partials/OrdersBlankSlate.blade.php
@extends('Shared.Layouts.BlankSlate')


@section('blankslate-icon-class')
    ico-cart
@stop

@section('blankslate-title')
    No Orders Yet
@stop

@section('blankslate-text')
    New orders will appear here as they are created.
@stop

@section('blankslate-body')

@stop

resources/views/ManageEvent/Partials/SurveyBlankSlate.blade.php
@extends('Shared.Layouts.BlankSlate')

@section('blankslate-icon-class')
    ico-question2
@stop

@section('blankslate-title')
    No Questions Yet
@stop

@section('blankslate-text')
    Here you can add questions which attendees will be asked to answer during the check-out process.
@stop

@section('blankslate-body')
    <button data-invoke="modal" data-modal-id='CreateQuestion' data-href="{{route('showCreateTicket', array('event_id'=>$event->id))}}" href='javascript:void(0);'  class=' btn btn-success mt5 btn-lg' type="button" >
        <i class="ico-question"></i>
        Create Question
    </button>
@stop

resources/views/ManageEvent/Partials/TicketDesignPreview.blade.php
{!! HTML::style(asset('assets/stylesheet/ticket.css')) !!}
<style>
    .ticket {
        border: 1px solid {{$event->ticket_border_color}};
        background: {{$event->ticket_bg_color}} ;
        color: {{$event->ticket_sub_text_color}};
        border-left-color: {{$event->ticket_border_color}} ;
    }
    .ticket h4 {color: {{$event->ticket_text_color}};}
    .ticket .logo {
        border-left: 1px solid {{$event->ticket_border_color}};
        border-bottom: 1px solid {{$event->ticket_border_color}};

    }
</style>
<div class="ticket">
    <div class="logo">
        {!! HTML::image(asset($event->organiser->full_logo_path)) !!}
    </div>

    <div class="event_details">
        <h4>Event</h4>Demo Event<h4>Organiser</h4>Demo Organiser<h4>Venue</h4>Demo Location<h4>Start Date / Time</h4>
        Mar 18th 4:08PM
        <h4>End Date / Time</h4>
        Mar 18th 5:08PM
    </div>

    <div class="attendee_details">
        <h4>Name</h4>Bill Blogs<h4>Ticket Type</h4>
        General Admission
        <h4>Order Ref.</h4>
        #YLY9U73
        <h4>Attendee Ref.</h4>
        #YLY9U73-1
        <h4>Price</h4>
        €XX.XX
    </div>

    <div class="barcode">
        {!! DNS2D::getBarcodeSVG('hello', "QRCODE", 6, 6) !!}
    </div>
</div>

resources/views/ManageEvent/Partials/TopNav.blade.php
@section('pre_header')
    @if(!$event->is_live)
        <style>
            .sidebar {
                top: 43px;
            }
        </style>
        <div class="alert alert-warning top_of_page_alert">
            This event is not visible to the public. <a href="{{route('MakeEventLive', ['event_id' => $event->id])}}">Click
                here to make it live</a> .
        </div>
    @endif
@stop
<ul class="nav navbar-nav navbar-left">
    <!-- Show Side Menu -->
    <li class="navbar-main">
        <a href="javascript:void(0);" class="toggleSidebar" title="Show sidebar">
            <span class="toggleMenuIcon">
                <span class="icon ico-menu"></span>
            </span>
        </a>
    </li>
    <!--/ Show Side Menu -->
    <li class="nav-button">
        <a target="_blank" href="{{$event->event_url}}">
            <span>
                <i class="ico-eye2"></i>&nbsp;Event Page
            </span>
        </a>
    </li>
</ul>